-- 코드를 입력하세요
SELECT 
    INS.ANIMAL_ID AS ANIMAL_ID,
    INS.ANIMAL_TYPE AS ANIMAL_TYPE,
    INS.NAME AS NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE
    INS.SEX_UPON_INTAKE LIKE 'Intact%' AND
    OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY INS.ANIMAL_ID