SELECT 
    M.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M 
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    -- 리뷰를 가장 많이 작성한 회원 ID 찾기
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (
        -- 최대 리뷰 개수 찾기
        SELECT MAX(REVIEW_COUNT) 
        FROM (
            SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS SubQuery
    )
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;